/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoxesSidebar: typeof import('./src/components/BoxesSidebar.vue')['default']
    CardOverlay: typeof import('./src/components/CardOverlay.vue')['default']
    EnlargeButton: typeof import('./src/components/EnlargeButton.vue')['default']
    GenericLayout: typeof import('./src/components/GenericLayout.vue')['default']
    GridLayout: typeof import('./src/components/GridLayout.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    PresetBoxcontent: typeof import('./src/components/PresetBoxcontent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rulebook: typeof import('./src/components/Rulebook.vue')['default']
    Rulebooks: typeof import('./src/components/Rulebooks.vue')['default']
    StaticCard: typeof import('./src/components/StaticCard.vue')['default']
    StaticCardWithSet: typeof import('./src/components/StaticCardWithSet.vue')['default']
    TextOverlay: typeof import('./src/components/TextOverlay.vue')['default']
  }
}
